title: National Recording Preservation Foundation
url: 'https://www.recordingpreservation.org'
baseurl: '/'
repository: 'recordingpreservation/nrpf-website'
permalink: pretty

analytics:
  google-gtag: 'G-MJB1L77T8N'

logo:
  mobile: "images/logo/NRPF_mandala_nobg_white.png"
  mobile_height: "100px"
  mobile_width: "100px"
  desktop: "images/logo/NRPF_mandala_nobg_white.png"
  desktop_height: "128px"
  desktop_width: ""

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
    permalink: /people/:title
  programs:
    output: true
    sort_by: weight
  news:
    output: true
    permalink: /news/:year/:title
  posts:
    output: true
    permalink: /features/:year/:title
  grants:
    output: true

defaults:
  - scope: 
      path: ""
    values:
      image: "/images/logo/nrpf-seal-624x596.jpeg"
  # posts
  - scope:
      type: "posts"
    values:
      layout: "post"
      image: "/images/social/NRPF-mandala-title-white-blue.png"
      fullWidth: "true"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"
      image: "/images/social/NRPF-mandala-title-white-blue.png"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news-item"
      image: "images/logo/nrpf-seal-624x596.jpeg"
  - scope:
      path: ""
      type: "grants"
    values:
      layout: "grant"
      image: "images/logo/nrpf-seal-624x596.jpeg"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

# reading files
# include _pages directory
include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"