title: National Recording Preservation Foundation
url: 'https://www.recordingpreservation.org'
baseurl: '/'
repository: 'recordingpreservation/nrpf-website'
permalink: pretty


logo:
  mobile: "images/logo/logo-mobile.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/nrpf-monogram-shadow-logo.png"
  desktop_height: "32px"
  desktop_width: ""

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
    permalink: /people/:title
  programs:
    output: true
    sort_by: weight
  news:
    output: true
    permalink: /news/:title
  posts:
    output: true
    permalink: /features/:year/:title
  grants:
    output: true

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      image: "images/logo/nrpf-seal-624x596.jpeg"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"
      image: "images/logo/nrpf-seal-624x596.jpeg"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news-item"
      image: "images/logo/nrpf-seal-624x596.jpeg"
  - scope:
      path: ""
      type: "grants"
    values:
      layout: "grant"
      image: "images/logo/nrpf-seal-624x596.jpeg"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
